# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idc',
            name='groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
