# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 07:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_idc_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='administrator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Admin'),
            preserve_default=False,
        ),
    ]
