# Generated by Django 2.2.4 on 2019-08-13 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0003_host_administrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='administrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                    verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='host',
            name='core_num',
            field=models.SmallIntegerField(
                choices=[(2, '2 Cores'), (4, '4 Cores'), (6, '6 Cores'), (8, '8 Cores'), (10, '10 Cores'),
                         (12, '12 Cores'), (14, '14 Cores'), (16, '16 Cores'), (18, '18 Cores'), (20, '20 Cores'),
                         (22, '22 Cores'), (24, '24 Cores'), (26, '26 Cores'), (28, '28 Cores')]),
        ),
        migrations.AlterField(
            model_name='host',
            name='service_type',
            field=models.CharField(
                choices=[('moniter', 'Moniter'), ('lvs', 'LVS'), ('db', 'Database'), ('analysis', 'Analysis'),
                         ('admin', 'Admin'), ('storge', 'Storge'), ('web', 'WEB'), ('email', 'Email'), ('mix', 'Mix')],
                max_length=32),
        ),
    ]
