# Generated by Django 2.2.16 on 2020-10-27 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_idc_is_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idc',
            name='is_valid',
        ),
    ]
